[package]
name = "razer-control-desktop"
version = "0.1.0"
description = "Tauri shell for the razer-control-secureblue web UI"
license = "GPL-2.0-only"
edition = "2024"

[lib]
name = "razer_control_desktop_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.6.3" }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
log = "0.4"
tauri = { version = "2.11.3" }
tauri-plugin-log = "2"
razer-control-secureblue = { path = "../.." }

[lints.rust]
unsafe_code = "forbid"
